stages:
  - test

before_script:
  - apt update -y
  - apt upgrade -y

test:
  stage: test
  image: python:latest
  script:
    - add-apt-repository ppa:jonathonf/vim
    - apt update -y
    - apt install -y vim
    - pip install vim-vint
    - make lint test
