stages:
  - test

test:
  stage: test
  image: debian:stable
  script:
    - apt update -y
    - apt upgrade -y
    - apt install -y git vim python-pip make
    - pip install vim-vint
    - make lint test
