stages:
  - test

test:
  stage: test
  image: python:latest
  script:
    - apt update -y
    - apt upgrade -y
    - apt install -y software-properties-common 
    - add-apt-repository ppa:jonathonf/vim
    - apt update -y
    - apt install -y vim
    - pip install vim-vint
    - make lint test
