stages:
  - test

before_script:
  - apt update -qy
  - apt upgrade -qy

test:
  stage: test
  image: python:latest
  script:
    - apt install -qy vim
    - pip install vim-vint
    - make lint test
